### ISSUE TITLE
GT2 Tension Meter - Increase Number/Tick Mark Depth?

### ISSUE THREAD

**Issue by awickham10** [Diyshift/3D-Printer#6]
Would it be possible to make the numbers and tick marks a little deeper? When doing a filament swap, it seems like the three layers or whatever isn't quite enough to get a good color. You can the color mismatch on West3D's page. Awesome project - I'm excited to give it a shot!

![image](https://github.com/Diyshift/3D-Printer/assets/7840633/b4487de3-16bd-4757-8cab-0c2f3685c298)

**Comment by Diyshift** [comment]
Thanks for reaching out!
You can probably disregard that image as it is an older version. The one pictured was using a translucent green wich I do not recommend. West 3D has since come out with their own Ambrosia ASA line and it much better in this and almost every other regard, this is what is used in all current production meters for West 3D.  I have included a shot of the current meters in  Ambrosia green. 
![image](https://github.com/Diyshift/3D-Printer/assets/1421653/c51df8e4-720b-49e6-a932-3374c6bd85a3)

When I tried deeper lettering it decreased the viewing angle so this was kind of a sweet spot for coverage and view angle. 

-PF

**Comment by awickham10** [comment]
I experienced the same thing with KVP Voron Red, but your point about the viewing angle is probably way more important than the color not matching 😂

Consider this one closed!
