### ISSUE TITLE
Why 70 Duro

### ISSUE THREAD

**Issue by cromine11** [Diyshift/3D-Printer#7]
I was looking into the calculators and I was wondering why you chose 70 Duro. From what I found 50 Duro was in the weight range for my 300 Trident. Did you do testing on the others and found this had the best results?

**Comment by Diyshift** [comment]
I got stiffer than spec due to the fact that there is a lot of moving mass up high didnt want the machine shaking violently and it ended up working out.  50 may work but they are pretty soft. Other users have experimented going a step down for their printers eg: 30 duro for a V0 and it ended up being too soft so 50 was the sweet spot for them despite being harder than spec. So I believe that for certain applications the durometer should be chosen based on the application AND weight as opposed to just weight alone. They have excellent calculators here if you really want to go down the rabbit hole ; )   https://www.sorbothane.com/technical-data/design-guide-calculators/vibration-calculator/
